services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=k6admin
      - INFLUXDB_ADMIN_PASSWORD=k6pass
    volumes:
      - influxdb_data:/var/lib/influxdb

  chronograf:
    image: chronograf:1.9
    container_name: chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

  k6:
    image: loadimpact/k6:0.45.0
    container_name: k6
    depends_on:
      - influxdb
    entrypoint: ["sleep", "infinity"]

volumes:
  influxdb_data:
  grafana_data: